config/routes.rb
Ezmodeling::Application.routes.draw do
  get "pages/home"

  get "pages/about"

  get "pages/contact"

  get "pages/help"

  resources :model_associations

  resources :controller_actions

  resources :resource_views

  resources :model_attributes

  resources :notes

  resources :projects

  resources :parts

  resources :desires
  
  root :to => 'projects#index'

end

app/models/part.rb
class Part < ActiveRecord::Base
  
  belongs_to :project
  
  has_many :model_attributes
  has_many :resource_views
  has_many :controller_actions
  has_one :note
  
  has_many :primary_model_associations,
            :class_name => "ModelAssociation",
            :foreign_key => "primary_model_id"
              
  has_many :secondary_model_associations,
            :class_name => "ModelAssociation",
            :foreign_key => "secondary_model_id"
  
  scope :app_models, where(:model_role => true)
  scope :app_controllers, where(:controller_role => true)
  scope :app_views, where(:view_role => true)
  
  validates :name, :presence => true
  validates :description, :presence => true
  
  
end

app/controllers/parts_controller.rb
class PartsController < ApplicationController
  # GET /parts
  # GET /parts.json
  def index
    @parts = Part.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @parts }
    end
  end

  # GET /parts/1
  # GET /parts/1.json
  def show
    @part = Part.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @part }
    end
  end

  # GET /parts/new
  # GET /parts/new.json
  def new
    @part = Part.new
    @part.project_id = params[:project_id]

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @part }
    end
  end

  # GET /parts/1/edit
  def edit
    @part = Part.find(params[:id])
  end

  # POST /parts
  # POST /parts.json
  def create
    @part = Part.new(params[:part])

    respond_to do |format|
      if @part.save
        format.html { redirect_to project_url(@part.project_id), notice: 'Part was successfully created.' }
        format.json { render json: @part, status: :created, location: @part }
      else
        format.html { render action: "new" }
        format.json { render json: @part.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /parts/1
  # PUT /parts/1.json
  def update
    @part = Part.find(params[:id])

    respond_to do |format|
      if @part.update_attributes(params[:part])
        format.html { redirect_to project_url(@part.project_id), notice: "#{@part.name.capitalize.pluralize} part successfully updated." }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @part.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /parts/1
  # DELETE /parts/1.json
  def destroy
    @part = Part.find(params[:id])
    projectid = @part.project_id
    @part.destroy

    respond_to do |format|
      format.html { redirect_to project_url(projectid), :notice => "You destroyed a part of your rails app. The horror! The horror!" }
      format.json { head :ok }
    end
  end
end

app/helpers/parts_helper.rb
module PartsHelper
end

app/views/parts/_controllers.html.erb
<p>

  <% if @controllers.blank? %>
  
    <h2>Controllers</h2>
  
    <blockquote><%= "Controllers are brains. Where are the brains of the operation? Identify a part above (that's inspired by your user stories and business logic) as a controller and you'll see it here. And you'll be able to do some more cool stuff with it." %></blockquote>
    
  <% else %>
  

    <h2>Controllers</h2>

    <table>
      <tr>
        <th>Name</th>
        <th>Actions</th>
        <th></th>
        <th></th>
        <th></th>
      </tr>

    <% @controllers.each do |controller| %>
      <tr>
    
        <td><%= controller.name.pluralize %></td>
          <% if controller.controller_actions.count < 1 %>
            <td>No controller actions!!!</td>
          <% else %>
            <td>
            <% controller.controller_actions.each do |controller_action| %>
              
              <% if controller_action.resource_view.blank? %>
                <%= controller_action.controller_method %> --> <%= "NO VIEW!" %> ...
              <% else %>
                <%= controller_action.controller_method %> --> <%= controller_action.resource_view.resource_url %> ...
              <% end %>
            
          <% end %>
            </td>
    <% end %>
    
        <td><%= link_to "Add/Modify Actions", new_controller_action_path(:current_part_id => controller.id) %></td>
    
        <% if controller.note.blank? %>
            <td><%= link_to " Add Note", new_note_path(:part_id => controller.id) %></td>
        <% else %>
            <td><%= link_to "See Notes", edit_note_path(controller.note.id) %></td>
        <% end %>
    
      </tr>
    <% end %>
  </table>

  <br />


  
  <% end %>
  
</p>

app/views/parts/_form.html.erb
<%= form_for(@part) do |f| %>
  <% if @part.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@part.errors.count, "error") %> prohibited this part from being saved:</h2>

      <ul>
      <% @part.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
    
    <i>Capitalization, spacing, and underscores matter. Use a form like User (names with one word) or User_Session (names with two words)</i><br />

  <div class="hidden field">
    <%= f.hidden_field :project_id, :value => @part.project_id %>
  </div>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :model_role, "Model?" %><br />
    <%= f.check_box :model_role %>
  </div>
  <div class="field">
    <%= f.label :view_role, "View?" %><br />
    <%= f.check_box :view_role %>
  </div>
  <div class="field">
    <%= f.label :controller_role, "Controller?" %><br />
    <%= f.check_box :controller_role %>
  </div>
  <div class="field">
    <%= f.label :seed_role, "Seed?" %><br />
    <%= f.check_box :seed_role %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/parts/_models.html.erb
<p>

  <% if @models.blank? %>
  
    <h2>Models</h2>
  
      <blockquote><%= "Rails is ideal for database-backed web apps. Where's your model that's got your back? Highly recommended that you identify at least one model (inspired by your user stories and business logic) ASAP." %></blockquote>

    
  <% else %>
  

  <h2>Models</h2>

  <table>
    <tr>
      <th>Name</th>
      <th>Attributes</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>

  <% @models.each do |model| %>
    <tr>
      <td><%= model.name.singularize %></td>
      <% if model.model_attributes.count < 1 %>
        <td>No attributes!!!</td>
      <% else %>
        <td>
          <% model.model_attributes.each do |attribute| %>
            <%= attribute.name %>:<%= attribute.attribute_type.description %>              
        <% end %>
        </td>
  <% end %>
      
      <td><%= link_to "Add/Modify Attributes", new_model_attribute_path(:current_part_id => model.id) %></td>
      
      <% if model.note.blank? %>
          <td><%= link_to " Add Note", new_note_path(:part_id => model.id) %></td>
      <% else %>
          <td><%= link_to "See Notes", edit_note_path(model.note.id) %></td>
      <% end %>
      
      
    </tr>
  <% end %>
  </table>

  <br />



  
  <% end %>
  
</p>

app/views/parts/_parts.html.erb
<p>

  <% if @parts.blank? %>
  
    <h2>Project Parts</h2>

      <p>
        <%= link_to "identify a new part", new_part_url(:project_id => @project.id) %>
        <%= "for your #{@project.name} app inspired by your user stories" %> 
      </p>
  
    <blockquote><%= "Your project parts are the 'things' that bring your app to life and help create something valuable for your users and your business" %></blockquote>
    
  <% else %>
  

  <h2>Project Parts</h2>

  <p>
    <%= link_to "identify a new part", new_part_url(:project_id => @project.id) %>
    <%= "for your #{@project.name} app inspired by your user stories" %> 
  </p>

  <table>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Model</th>
      <th>View</th>
      <th>Controller</th>
      <th>Seed</th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
    </tr>

  <% @parts.each do |part| %>
    <tr>
      <td><%= part.name.pluralize %></td>
      <td><%= part.description %></td>
      <td><%= yes_or_no part.model_role %></td>
      <td><%= yes_or_no part.view_role %></td>
      <td><%= yes_or_no part.controller_role %></td>
      <td><%= yes_or_no part.seed_role %></td>
      <td><%= link_to "Edit", edit_part_path(part.id) %></td>
      <td><%= link_to "Delete", part, :confirm => "Really want to part ways with your rails part?", :method => :delete %></td>
      <% if part.note.blank? %>
          <td><%= link_to " Add Note", new_note_path(:part_id => part.id) %></td>
      <% else %>
          <td><%= link_to "See Notes", edit_note_path(part.note.id) %></td>
      <% end %>  
    </tr>
  <% end %>
  </table>

  <br />


  
  <% end %>
  
</p>

app/views/parts/_relationships.html.erb
<p>

  <% if @models.count < 2 %>
  
    <h1>Associations</h1>
  
      <blockquote>When you identify two or more parts (inspired by your user stories) as models, they'll be listed here, and you can figure out what kind of relationships they have to one another, if any.</blockquote>

    
  <% else %>
  

  <h1>Associations</h1>

      <blockquote>Associations are relationships between different models. (Ex: belongs_to or has_many). In this section, you can identify the associations between different models if there are any.</blockquote>


    <table>
      <tr>
        <th>Model Name</th>
        <th>Model Associations</th>
        <th></th>
        <th></th>
        <th></th>
      </tr>

    <% @models.each do |model| %>
      <tr>
    
        <td><%= model.name.singularize %></td>
          <% if model.primary_model_associations.count < 1 %>
            <td>Independent model!!! Flying Solo!!!</td>
          <% else %>
            <td>
            <% model.primary_model_associations.each do |primary_model_association| %>
            <%= "#{primary_model_association.secondary_model.name.singularize} (#{primary_model_association.association_type.name} #{primary_model_association.association_name})" %>
          <% end %>
            </td>
    <% end %>
    
        <td><%= link_to "Add/Modify Associations", new_model_association_path(:primary_model_id => model.id) %></td>
    
        <% if model.note.blank? %>
            <td><%= link_to " Add Note", new_note_path(:part_id => model.id) %></td>
        <% else %>
            <td><%= link_to "See Notes", edit_note_path(model.note.id) %></td>
        <% end %>
    
      </tr>
    <% end %>
  </table>

  <br />


  
  <% end %>
  
</p>

app/views/parts/_views.html.erb
<p>

  <% if @views.blank? %>
  
    <h2>Views</h2>
  
      <blockquote><%= "There's no show, if you're not providing anything to see! What will your users see, and how will they see it? As you identify parts (inspired by your user stories and business logic) as views, they will appear here. And you'll have something to see. Oh, the irony. (According to Alanis Morissette's understanding of irony.)" %></blockquote>

    
  <% else %>
  

  <h2>Views</h2>

  <table>
    <tr>
      <th>Name</th>
      <th>URLs</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>



  <% @views.each do |view| %>
    <tr>
      <td><%= view.name.pluralize %></td>
        <% if view.resource_views.count < 1 %>
          <td>No URLs for your views!!!</td>
        <% else %>
          <td>
          <% view.resource_views.each do |resource_view| %>
            <%= resource_view.resource_url %> ...
        <% end %>
          </td>            
       
  <% end %>
        
      <td><%= link_to "Add/Modify Views", new_resource_view_path(:current_part_id => view.id) %></td>
        
      
      <% if view.note.blank? %>
          <td><%= link_to " Add Note", new_note_path(:part_id => view.id) %></td>
      <% else %>
          <td><%= link_to "See Notes", edit_note_path(view.note.id) %></td>
      <% end %>
      
    </tr>
  <% end %>
  </table>

  <br />


  
  <% end %>
  
</p>

app/views/parts/edit.html.erb
<h2>Editing <%= @part.name.pluralize %></h2>

<%= render 'form' %>

<%= link_to 'Back', project_path(@part.project_id) %>

app/views/parts/index.html.erb
<h1>Listing parts</h1>

<table>
  <tr>
    <th>Project</th>
    <th>Name</th>
    <th>Description</th>
    <th>Controller role</th>
    <th>Model role</th>
    <th>View role</th>
    <th>Seed role</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @parts.each do |part| %>
  <tr>
    <td><%= part.project_id %></td>
    <td><%= part.name %></td>
    <td><%= part.description %></td>
    <td><%= part.controller_role %></td>
    <td><%= part.model_role %></td>
    <td><%= part.view_role %></td>
    <td><%= part.seed_role %></td>
    <td><%= link_to 'Show', part %></td>
    <td><%= link_to 'Edit', edit_part_path(part) %></td>
    <td><%= link_to 'Destroy', part, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Part', new_part_path %>

app/views/parts/new.html.erb
<h1>New part for <%= @part.project.name %></h1>

<%= render 'form' %>

<%= link_to 'Back', project_path(@part.project_id) %>

app/views/parts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Project:</b>
  <%= @part.project_id %>
</p>

<p>
  <b>Name:</b>
  <%= @part.name %>
</p>

<p>
  <b>Description:</b>
  <%= @part.description %>
</p>

<p>
  <b>Controller role:</b>
  <%= @part.controller_role %>
</p>

<p>
  <b>Model role:</b>
  <%= @part.model_role %>
</p>

<p>
  <b>View role:</b>
  <%= @part.view_role %>
</p>

<p>
  <b>Seed role:</b>
  <%= @part.seed_role %>
</p>


<%= link_to 'Edit', edit_part_path(@part) %> |
<%= link_to 'Back', parts_path %>