config/routes.rb
Ezmodeling::Application.routes.draw do
  get "pages/home"

  get "pages/about"

  get "pages/contact"

  get "pages/help"

  resources :model_associations

  resources :controller_actions

  resources :resource_views

  resources :model_attributes

  resources :notes

  resources :projects

  resources :parts

  resources :desires
  
  root :to => 'projects#index'

end

app/controllers/controller_actions_controller.rb
class ControllerActionsController < ApplicationController
  # GET /controller_actions
  # GET /controller_actions.json
  def index
    @controller_actions = ControllerAction.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @controller_actions }
    end
  end

  # GET /controller_actions/1
  # GET /controller_actions/1.json
  def show
    @controller_action = ControllerAction.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @controller_action }
    end
  end

  # GET /controller_actions/new
  # GET /controller_actions/new.json
  def new
    @controller_action = ControllerAction.new
    @part = Part.find_by_id(params[:current_part_id])
    @project = @part.project

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @controller_action }
    end
  end

  # GET /controller_actions/1/edit
  def edit
    @controller_action = ControllerAction.find(params[:id])
    @part = @controller_action.part
    @project = @part.project
  end

  # POST /controller_actions
  # POST /controller_actions.json
  def create
    @controller_action = ControllerAction.new(params[:controller_action])

    respond_to do |format|
      if @controller_action.save
        format.html { redirect_to new_controller_action_path(:current_part_id => @controller_action.part.id), notice: 'Controller action was successfully created.' }
        format.json { render json: @controller_action, status: :created, location: @controller_action }
      else
        format.html { redirect_to new_controller_action_path(:current_part_id => @controller_action.part.id), notice: "Didn't work!!! Did you enter a controller method?" }
        format.json { render json: @controller_action.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /controller_actions/1
  # PUT /controller_actions/1.json
  def update
    @controller_action = ControllerAction.find(params[:id])

    respond_to do |format|
      if @controller_action.update_attributes(params[:controller_action])
        format.html { redirect_to new_controller_action_path(:current_part_id => @controller_action.part.id), notice: 'Controller action was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @controller_action.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /controller_actions/1
  # DELETE /controller_actions/1.json
  def destroy
    @controller_action = ControllerAction.find(params[:id])
    @part = @controller_action.part.id
    @controller_action.destroy

    respond_to do |format|
      format.html { redirect_to new_controller_action_path(:current_part_id => @part), notice: "You destroyed a controller method! Is there a method to your madness?" }
      format.json { head :ok }
    end
  end
end

app/helpers/controller_actions_helper.rb
module ControllerActionsHelper
end

app/views/controller_actions/_editform.html.erb
<%= form_for(@controller_action) do |f| %>
  <% if @controller_action.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@controller_action.errors.count, "error") %> prohibited this controller_action from being saved:</h2>
      <ul>
      <% @controller_action.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="field">
    <%= f.label :controller_method, "Controller Method" %><br />
    <%= f.text_field :controller_method %>
  </div>
  <div class="field">
    <%= f.label :resource_view_id, "View" %><br />
    <%= f.collection_select :resource_view_id, @project.resource_views, :id, :resource_url %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/controller_actions/_form.html.erb
<%= form_for(@controller_action) do |f| %>
  <% if @controller_action.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@controller_action.errors.count, "error") %> prohibited this controller_action from being saved:</h2>

      <ul>
      <% @controller_action.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="hidden field">
    <br />
    <%= f.hidden_field :part_id, :value => @part.id %>
  </div>
  <div class="field">
    <%= f.label :controller_method, "Controller Method" %><br />
    <%= f.text_field :controller_method %>
  </div>
  <div class="field">
    <%= f.label :resource_view_id, "View" %><br />
    <%= f.collection_select :resource_view_id, @project.resource_views, :id, :resource_url %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/controller_actions/edit.html.erb
<h2>Editing controller action for <%= @controller_action.part.name.pluralize %> controller</h2>

<p>A controller action is a pairing of a controller method and a view.</p>

<p>Conventional controller methods: index, show, new, create, edit, update, destroy</p>

<%= render 'editform' %>

<%= link_to 'Back', project_path(@controller_action.part.project_id) %>

app/views/controller_actions/index.html.erb
<h1>Listing controller_actions</h1>

<table>
  <tr>
    <th>Id</th>
    <th>Part</th>
    <th>Controller method</th>
    <th>Resource view</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @controller_actions.each do |controller_action| %>
  <tr>
    <td><%= controller_action.id %></td>
    <td><%= controller_action.part_id %></td>
    <td><%= controller_action.controller_method %></td>
    <td><%= controller_action.resource_view_id %></td>
    <td><%= link_to 'Show', controller_action %></td>
    <td><%= link_to 'Edit', edit_controller_action_path(controller_action) %></td>
    <td><%= link_to 'Destroy', controller_action, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Controller action', new_controller_action_path %>

app/views/controller_actions/new.html.erb
<h2>Create new controller action for <%= @part.name.pluralize %> controller</h2>

<p>A controller action is a pairing of a controller method and a view.</p>

<p>Conventional controller methods: index, show, new, create, edit, update, destroy</p>

<%= render 'form' %>

</br>

<h3>Actions for <%= @part.name.pluralize %> controller</h3>

<% @part.controller_actions.each do |controller_action| %>
  <p><%= controller_action.controller_method %> --> <%= controller_action.resource_view.resource_url %>
    <%= link_to "Edit", edit_controller_action_path(controller_action.id) %>
    <%= link_to "Destroy", controller_action_path(controller_action.id), :method => "delete", :confirm => "You sure about this?" %>
  </p>

<% end %>

<%= link_to 'Back', project_path(@part.project_id) %>

app/views/controller_actions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Id:</b>
  <%= @controller_action.id %>
</p>

<p>
  <b>Part:</b>
  <%= @controller_action.part_id %>
</p>

<p>
  <b>Controller method:</b>
  <%= @controller_action.controller_method %>
</p>

<p>
  <b>Resource view:</b>
  <%= @controller_action.resource_view_id %>
</p>


<%= link_to 'Edit', edit_controller_action_path(@controller_action) %> |
<%= link_to 'Back', controller_actions_path %>