config/routes.rb
Ezmodeling::Application.routes.draw do
  get "pages/home"

  get "pages/about"

  get "pages/contact"

  get "pages/help"

  resources :model_associations

  resources :controller_actions

  resources :resource_views

  resources :model_attributes

  resources :notes

  resources :projects

  resources :parts

  resources :desires
  
  root :to => 'projects#index'

end

app/models/desire.rb
class Desire < ActiveRecord::Base
  
  belongs_to :project
  has_one :note
  
  scope :user_stories, where(:desire_type => "User Stories")
  scope :business_logic, where(:desire_type => "Business Logic")
  
  def hasnotes?
    self.notes.count > 0
  end
  
  
end

app/controllers/desires_controller.rb
class DesiresController < ApplicationController
  # GET /desires
  # GET /desires.json
  def index
    @desires = Desire.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @desires }
    end
  end

  # GET /desires/1
  # GET /desires/1.json
  def show
    @desire = Desire.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @desire }
    end
  end

  # GET /desires/new
  # GET /desires/new.json
  def new
    @desire = Desire.new
    @desire.desire_type = params[:desire_type]
    @desire.project_id = params[:project_id]
    
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @desire }
    end
  end

  # GET /desires/1/edit
  def edit
    @desire = Desire.find(params[:id])
  end

  # POST /desires
  # POST /desires.json
  def create
    @desire = Desire.new(params[:desire])


    respond_to do |format|
      if @desire.save
        format.html { redirect_to project_path(@desire.project), :notice => "You successfully added a new item to #{@desire.desire_type}"}
        format.json { render json: @desire, status: :created, location: @desire }
      else
        format.html { render action: "new" }
        format.json { render json: @desire.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /desires/1
  # PUT /desires/1.json
  def update
    @desire = Desire.find(params[:id])

    respond_to do |format|
      if @desire.update_attributes(params[:desire])
        format.html { redirect_to project_url(@desire.project_id), notice: "#{@desire.desire_type} successfully updated." }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @desire.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /desires/1
  # DELETE /desires/1.json
  def destroy
    @desire = Desire.find(params[:id])
    expiring_desire = @desire
    @desire.destroy

    respond_to do |format|
      format.html { redirect_to project_url(expiring_desire.project.id), :notice => "You successfully deleted your #{expiring_desire.desire_type.singularize}" }
      format.json { head :ok }
    end
  end
end

app/helpers/desires_helper.rb
module DesiresHelper
end

app/views/desires/_businesslogic.html.erb
<p>

  <% if @desires.business_logic.blank? %>
  
    <h2>Business Logic</h2>

    <p><%= link_to "create new", new_desire_path(:desire_type => "Business Logic", :project_id => @project.id) %></p>
  
    <blockquote><%= "Business logic is how you want to run things and make things happen." %></blockquote>
    
  <% else %>
  

  <h2>Business Logic</h2>

  <p><%= link_to "create new", new_desire_path(:desire_type => "Business Logic", :project_id => @project.id) %></p>

  <table>
    <tr>
      <th></th>
      <th>As a business owner and/or rails developer I want to...</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>

  <% @desires.business_logic.each do |desire| %>
    <tr>
      <td><%= check_box_tag desire.done %></td>
      <td><%= desire.description %></td>
      <td><%= link_to "Edit", edit_desire_path(desire.id) %></td>
      <td><%= link_to "Delete", desire, :confirm => "You sure about this?", :method => :delete %></td>
    </tr>
  <% end %>
  </table>

  <br />


  
  <% end %>
  
</p>

app/views/desires/_form.html.erb
<%= form_for(@desire) do |f| %>
  <% if @desire.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@desire.errors.count, "error") %> prohibited this desire from being saved:</h2>

      <ul>
      <% @desire.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  

  <div class="field">
    <% if @desire.desire_type == "User Stories" %>
      <%= f.label :description, "As a user, I want to..." %><br />
    <% else %>
      <%= f.label :description, "As a business owner and/or rails app developer, I want to..." %><br />
    <% end %>
    <%= f.text_field :description %><br />
    <br />
    <%= f.label :done, "Completed?" %>
    <%= f.check_box :done %>
  </div>

  <div class="hidden field">
    <%= f.hidden_field :desire_type, :value => @desire.desire_type %>
  </div>
  
  <div class="field">
    <%= f.hidden_field :project_id, :value => @desire.project_id %>
  </div>
  
  <div class="actions">
    <%= f.submit "Proceed with #{@desire.desire_type.singularize}" %>
  </div>
  
<% end %>

app/views/desires/_userstories.html.erb
<p>

  <% if @desires.user_stories.blank? %>
  
    <h2>User Stories</h2>

    <p><%= link_to "create new", new_desire_path(:desire_type => "User Stories", :project_id => @project.id) %></p>
  
    <blockquote><%= "No user stories! Create some to give your rails app a clear sense of direction and help you plan it." %></blockquote>
    
  <% else %>
  

  <h2>User Stories</h2>

  <p><%= link_to "create new", new_desire_path(:desire_type => "User Stories", :project_id => @project.id) %></p>

  <table>
    <tr>
      <th></th>
      <th>As a user I want to...</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>

  <% @desires.user_stories.each do |desire| %>
    <tr>
      
      <% if desire.done == true %>
          <td><%= check_box_tag :desire_id, :yes, true%></td>
      <% else %>
          <td><%= check_box_tag :desire_id %></td> 
      <% end %>
      
        <td><%= desire.description %></td>
        <td><%= link_to "Edit", edit_desire_path(desire.id) %></td>
        <td><%= link_to "Delete", desire, :confirm => "You sure about this?", :method => :delete %></td>

        
        
        <% if desire.note.blank? %>
            <td><%= link_to " Add Note", new_note_path(:desire_id => desire.id) %></td>
        <% else %>
            <td><%= link_to "See Notes", edit_note_path(desire.note.id) %></td>
        <% end %>
    </tr>
  <% end %>
  </table>

  <br />


  
  <% end %>
  
</p>

app/views/desires/edit.html.erb
<h2>Editing <%= @desire.desire_type.singularize %></h2>

<%= render 'form' %>

<%= link_to 'Back', project_path(@desire.project.id) %>

app/views/desires/index.html.erb
<h1>Listing desires</h1>

<table>
  <tr>
    <th>Description</th>
    <th>Desire Type</th>
    <th>Project</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @desires.each do |desire| %>
  <tr>
    <td><%= desire.description %></td>
    <td><%= desire.desire_type %></td>
    <td><%= desire.project.name %></td>
    <td><%= link_to 'Show', desire %></td>
    <td><%= link_to 'Edit', edit_desire_path(desire) %></td>
    <td><%= link_to 'Destroy', desire, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Desire', new_desire_path %>

app/views/desires/new.html.erb
<h2>New <%= @desire.desire_type.singularize %></h2>

<%= render 'form' %>

<%= link_to 'Back', project_path(@desire.project.id) %>

app/views/desires/show.html.erb
<p id="notice"><%= notice %></p>


<p>
  <b>Description:</b>
  <%= @desire.description %>
</p>

<p>
  <b>Desire Type:</b>
  <%= @desire.desire_type %>
</p>

<p>
  <b>Project for Desire:</b>
  <%= @desire.project.name %>
</p>

<p>
  <b>Done:</b>
  <%= @desire.done %>
</p>


<%= link_to 'Edit', edit_desire_path(@desire) %> |
<%= link_to 'Back', desires_path %>