config/routes.rb
Ezmodeling::Application.routes.draw do
  get "pages/home"

  get "pages/about"

  get "pages/contact"

  get "pages/help"

  resources :model_associations

  resources :controller_actions

  resources :resource_views

  resources :model_attributes

  resources :notes

  resources :projects

  resources :parts

  resources :desires
  
  root :to => 'projects#index'

end

app/controllers/resource_views_controller.rb
class ResourceViewsController < ApplicationController
  # GET /resource_views
  # GET /resource_views.json
  def index
    @resource_views = ResourceView.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @resource_views }
    end
  end

  # GET /resource_views/1
  # GET /resource_views/1.json
  def show
    @resource_view = ResourceView.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @resource_view }
    end
  end

  # GET /resource_views/new
  # GET /resource_views/new.json
  def new
    @resource_view = ResourceView.new
    @part = Part.find_by_id(params[:current_part_id])

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @resource_view }
    end
  end

  # GET /resource_views/1/edit
  def edit
    @resource_view = ResourceView.find(params[:id])
    @part = Part.find_by_id(params[@resource_view.part_id])
  end

  # POST /resource_views
  # POST /resource_views.json
  def create
    @resource_view = ResourceView.new(params[:resource_view])

    respond_to do |format|
      if @resource_view.save
        format.html { redirect_to new_resource_view_path(:current_part_id => @resource_view.part_id), notice: 'Resource view was successfully created.' }
        format.json { render json: @resource_view, status: :created, location: @resource_view }
      else
        format.html { redirect_to new_resource_view_path(:current_part_id => @resource_view.part_id), notice: "Didn't work!!! Did you enter in a URL?" }
        format.json { render json: @resource_view.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /resource_views/1
  # PUT /resource_views/1.json
  def update
    @resource_view = ResourceView.find(params[:id])

    respond_to do |format|
      if @resource_view.update_attributes(params[:resource_view])
        format.html { redirect_to new_resource_view_path(:current_part_id => @resource_view.part_id), notice: 'Resource view was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @resource_view.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /resource_views/1
  # DELETE /resource_views/1.json
  def destroy
    @resource_view = ResourceView.find(params[:id])
    @part_id = @resource_view.part.id
    @resource_view.destroy

    respond_to do |format|
      format.html { redirect_to new_resource_view_path(:current_part_id => @part_id), notice: 'You killed your view!!! Which means that this is A View To a Kill. Cue Duran Duran.' }
      format.json { head :ok }
    end
  end
end

app/helpers/resource_views_helper.rb
module ResourceViewsHelper
end

app/views/resource_views/_editform.html.erb
<%= form_for(@resource_view) do |f| %>
  <% if @resource_view.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@resource_view.errors.count, "error") %> prohibited this resource_view from being saved:</h2>

      <ul>
      <% @resource_view.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :resource_url, "URL" %> 
    <%= f.text_field :resource_url %>
  </div>
  <div class="field">
    <%= f.label :description %>
    <%= f.text_field :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/resource_views/_form.html.erb
<%= form_for(@resource_view) do |f| %>
  <% if @resource_view.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@resource_view.errors.count, "error") %> prohibited this resource_view from being saved:</h2>

      <ul>
      <% @resource_view.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class=" hidden field">
    <br />
    <%= f.hidden_field :part_id, :value => @part.id %>
  </div>
  <div class="hidden field">
    <%= f.hidden_field :project_id, :value => @part.project.id %>
  <div class="field">
    <%= f.label :resource_url, "URL" %> 
    <%= f.text_field :resource_url %>
  </div>
  <div class="field">
    <%= f.label :description %>
    <%= f.text_field :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/resource_views/edit.html.erb
<h1>Editing URL for <%= "#{@resource_view.part.name.pluralize.capitalize} resource" %></h1>

<%= render 'editform' %>

app/views/resource_views/index.html.erb
<h1>Listing resource_views</h1>

<table>
  <tr>
    <th>Part</th>
    <th>Resource url</th>
    <th>Description</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @resource_views.each do |resource_view| %>
  <tr>
    <td><%= resource_view.part_id %></td>
    <td><%= resource_view.resource_url %></td>
    <td><%= resource_view.description %></td>
    <td><%= link_to 'Show', resource_view %></td>
    <td><%= link_to 'Edit', edit_resource_view_path(resource_view) %></td>
    <td><%= link_to 'Destroy', resource_view, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Resource view', new_resource_view_path %>

app/views/resource_views/new.html.erb
<h2>Create new URL for <%= @part.name.pluralize %> resource</h2>

<p>Examples of conventional URLs and their descriptions:</p>

<ul>
  <p>
    <li> 
    <%= "/#{@part.name.pluralize.downcase} (#{@part.name.pluralize.downcase}_path)" %> </br>
    <%= "lists an index of all #{@part.name.pluralize.downcase}" %>
    </li>
  </p>
  <p>
    <li> 
    <%= "/#{@part.name.pluralize.downcase}/new (new_#{@part.name.singularize.downcase}_path)" %> </br>
    <%= "enter details for a new #{@part.name.singularize.downcase}" %>
    </li>
  </p>
  <p>
    <li> 
    <%= "/#{@part.name.pluralize.downcase}/:id/edit (edit_#{@part.name.singularize.downcase}_path)" %> </br>
    <%= "edit details of a  #{@part.name.singularize.downcase} that has already been created" %>
    </li>
  </p>
  <p>
    <li> 
    <%= "/#{@part.name.pluralize.downcase}/:id (#{@part.name.singularize.downcase}_path)" %> </br>
    <%= "shows the details of a particular #{@part.name.singularize.downcase}" %>
    </li>
  </p>  
  
  
</ul>

<%= render 'form' %>

</br>

<h3>URLs for <%= @part.name.pluralize %> resource</h3>

<% @part.resource_views.each do |resource_view| %>
  <p><%= resource_view.resource_url %> : <%= resource_view.description %>
    <%= link_to "Edit", edit_resource_view_path(resource_view.id) %>
    <%= link_to "Destroy", resource_view_path(resource_view.id), :method => "delete", :confirm => "You sure about this?" %>
  </p>

<% end %>

<%= link_to 'Back', project_path(@part.project_id) %>

app/views/resource_views/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Part:</b>
  <%= @resource_view.part_id %>
</p>

<p>
  <b>Resource url:</b>
  <%= @resource_view.resource_url %>
</p>

<p>
  <b>Description:</b>
  <%= @resource_view.description %>
</p>


<%= link_to 'Edit', edit_resource_view_path(@resource_view) %> |
<%= link_to 'Back', resource_views_path %>